services:
  survey-ms-db:
    image: postgres:latest
    container_name: survey-ms-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: survey-ms-db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "survey-ms-db"]
      interval: 10s
      timeout: 5s
      retries: 1
      start_period: 10s

    networks:
      - zettaloan

  survey-ms:
    image: survey-ms
    container_name: survey-ms
    ports:
      - "9030:9030"
    environment:
      SPRING_APPLICATION_NAME: "survey-ms"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://survey-ms-db:5432/survey-ms-db"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: test
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8900/eureka/
    depends_on:
      survey-ms-db:
        condition: service_healthy
      # eureka-server:
      #   condition: service_healthy
    networks:
      - zettaloan

networks:
  zettaloan:
    driver: "bridge"
